package com.antvance.finance;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;

public class MainActivity extends Activity {
    LinearLayout root, content, nav;
    int red=Color.rgb(255,59,69), green=Color.rgb(70,214,155), bg=Color.rgb(5,7,11), panel=Color.rgb(17,21,29), muted=Color.rgb(143,152,168), white=Color.rgb(245,247,250);
    android.content.SharedPreferences prefs;
    int waits, points, trades;
    int dp(float v){ return (int)(v*getResources().getDisplayMetrics().density+.5f); }
    TextView tv(String s,float size,int color){ TextView t=new TextView(this); t.setText(s); t.setTextSize(size); t.setTextColor(color); t.setGravity(Gravity.CENTER_VERTICAL); t.setPadding(dp(2),dp(2),dp(2),dp(2)); return t; }
    GradientDrawable bg(int color,float r){ GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(r)); return g; }
    Button btn(String s,int color){ Button b=new Button(this); b.setText(s); b.setTextColor(white); b.setTextSize(14); b.setAllCaps(false); b.setBackground(bg(color,18)); b.setPadding(dp(12),0,dp(12),0); return b; }
    LinearLayout col(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); return l; }
    LinearLayout row(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.HORIZONTAL); l.setGravity(Gravity.CENTER_VERTICAL); return l; }
    TextView small(String s){ return tv(s,12,muted); }
    TextView title(String s){ TextView t=tv(s,22,white); t.setTypeface(null,1); return t; }
    TextView cardText(String s,float size,int color){ TextView t=tv(s,size,color); t.setPadding(dp(14),dp(12),dp(14),dp(12)); t.setBackground(bg(panel,16)); return t; }
    @Override public void onCreate(Bundle b){ super.onCreate(b); getWindow().setStatusBarColor(bg); getWindow().setNavigationBarColor(bg); prefs=getSharedPreferences("data",0); waits=prefs.getInt("waits",4); points=prefs.getInt("points",1250); trades=prefs.getInt("trades",3); showHome(); }
    void base(){ root=col(); root.setBackgroundColor(bg); ScrollView scroll=new ScrollView(this); scroll.setFillViewport(true); content=col(); content.setPadding(dp(18),dp(18),dp(18),dp(18)); scroll.addView(content); root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1)); nav=row(); nav.setPadding(dp(10),dp(8),dp(10),dp(8)); nav.setBackgroundColor(Color.rgb(9,12,17)); root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70))); setContentView(root); addNav("⌂\n홈",()->showHome()); addNav("▣\n일지",()->showJournal()); addNav("♧\n알림",()->showAlerts()); addNav("♢\n보상",()->showRewards()); addNav("⋯\n더보기",()->showMore()); }
    void addNav(String s, final Runnable r){ TextView n=tv(s,11,muted); n.setGravity(Gravity.CENTER); nav.addView(n,new LinearLayout.LayoutParams(0,-1,1)); n.setOnClickListener(v->r.run()); }
    void header(String sub){ LinearLayout h=row(); TextView logo=tv("ANTVANCE\nFINANCE",16,white); logo.setTypeface(null,1); h.addView(logo,new LinearLayout.LayoutParams(0,dp(52),1)); TextView gear=tv("⚙",23,white); h.addView(gear,new LinearLayout.LayoutParams(dp(45),dp(52))); gear.setGravity(Gravity.CENTER); gear.setOnClickListener(v->showMore()); content.addView(h); if(sub!=null){ TextView x=small(sub); x.setPadding(0,0,0,dp(14)); content.addView(x); } }
    TextView section(String s){ TextView t=tv(s,15,white); t.setTypeface(null,1); t.setPadding(0,dp(18),0,dp(10)); content.addView(t); return t; }
    void showHome(){ base(); header("오늘도 차분한 투자를 응원해요"); LinearLayout stats=row(); stats.setWeightSum(3); stats.addView(stat("오늘 매매",""+trades+"회","목표 5회 이하"),w()); stats.addView(stat("참은 횟수",""+waits+"회","목표 5회"),w()); stats.addView(stat("멘탈 상태","좋음","🙂 안정"),w()); content.addView(stats); section("멘탈 온도계"); content.addView(cardText("현재 상태  65%\n\n██████████████░░░░░░\n\n지금은 비교적 안정적인 상태예요.",14,white)); section("오늘의 뇌동매매 위험도"); content.addView(cardText("낮음  ·  28/100\n\n최근 기록에서 충동적인 매매 신호가 많지 않아요.\n\n오늘의 매매 원칙\n“좋은 투자는 기다리는 것에서 시작한다.”",14,white)); LinearLayout actions=row(); actions.setPadding(0,dp(14),0,0); Button wait=btn("30초 기다리기",red); Button journal=btn("매매일지 기록",Color.rgb(34,40,51)); actions.addView(wait,new LinearLayout.LayoutParams(0,dp(52),1)); actions.addView(journal,new LinearLayout.LayoutParams(0,dp(52),1)); wait.setOnClickListener(v->cooldown()); journal.setOnClickListener(v->showJournal()); content.addView(actions); }
    LinearLayout stat(String a,String b,String c){ LinearLayout l=col(); l.setPadding(dp(10),dp(10),dp(10),dp(10)); l.setBackground(bg(panel,14)); l.addView(small(a)); TextView y=tv(b,19,white); y.setTypeface(null,1); l.addView(y); l.addView(small(c)); return l; }
    LinearLayout.LayoutParams w(){ return new LinearLayout.LayoutParams(0,dp(92),1); }
    void cooldown(){ final Dialog d=new Dialog(this); LinearLayout l=col(); l.setPadding(dp(24),dp(24),dp(24),dp(20)); l.setBackground(bg(Color.rgb(10,13,19),26)); TextView x=tv("잠깐! 매수하기 전에\n다시 한 번 생각해보세요.",20,white); x.setTypeface(null,1); l.addView(x); TextView timer=tv("30",54,red); timer.setGravity(Gravity.CENTER); l.addView(timer,new LinearLayout.LayoutParams(-1,dp(110))); l.addView(cardText("“충동은 멈추고, 실력은 쌓는다.”\n\n지금 이 매매는 미리 세운 계획에 포함되어 있나요?",14,white)); Button wait=btn("기다릴게요  (+포인트)",red); l.addView(wait,new LinearLayout.LayoutParams(-1,dp(52))); Button close=btn("닫기",Color.TRANSPARENT); l.addView(close,new LinearLayout.LayoutParams(-1,dp(48))); d.setContentView(l); Window w=d.getWindow(); if(w!=null){ w.setBackgroundDrawableResource(android.R.color.transparent); w.setLayout(dp(340),-2); } final int[] sec={30}; final Handler h=new Handler(); Runnable rr=new Runnable(){ public void run(){ if(sec[0]>0){ timer.setText(""+sec[0]); sec[0]--; h.postDelayed(this,1000);} else {timer.setText("✓"); timer.setTextColor(green); wait.setText("기다리기 성공  +100P"); } }}; h.post(rr); wait.setOnClickListener(v->{ waits++; points+=100; save(); d.dismiss(); showHome(); }); close.setOnClickListener(v->d.dismiss()); d.show(); }
    void showJournal(){ base(); header("캡처 1장으로 매매일지를 간단하게"); section("체결 화면 캡처"); content.addView(cardText("📷  체결 화면을 선택하면\n종목 · 금액 · 시간이 자동으로 채워지는 구조입니다.\n\n※ 데모 버전에서는 화면 선택과 기록 흐름을 먼저 구현했습니다.",14,white)); Button pick=btn("캡처 이미지 선택",red); content.addView(pick,new LinearLayout.LayoutParams(-1,dp(52))); pick.setOnClickListener(v->{ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.setType("image/*"); i.addCategory(Intent.CATEGORY_OPENABLE); startActivityForResult(i,101); }); section("기록된 매매"); content.addView(cardText("매매 기록 예시\n68,200원  ·  오늘 10:23\n감정  차분함 🙂",15,white)); section("감정 태그"); LinearLayout tags=row(); String[] ts={"🙂 차분함","😟 불안","😡 욕심","😔 후회"}; for(String s:ts){ TextView t=cardText(s,12,white); tags.addView(t,new LinearLayout.LayoutParams(0,dp(48),1)); } content.addView(tags); Button saveb=btn("일지 저장하기",red); content.addView(saveb,new LinearLayout.LayoutParams(-1,dp(52))); saveb.setOnClickListener(v->Toast.makeText(this,"매매일지가 저장됐어요.",Toast.LENGTH_SHORT).show()); }
    @Override protected void onActivityResult(int req,int result,Intent data){ super.onActivityResult(req,result,data); if(req==101 && result==RESULT_OK && data!=null) Toast.makeText(this,"캡처를 불러왔어요. 감정 태그를 선택해 기록을 완성하세요.",Toast.LENGTH_LONG).show(); }
    void showAlerts(){ base(); header("계좌 연동 없이 쓰는 간편 알림"); section("프리셋"); String[] a={"📉 고점 대비 -5%\n매수가 대비 -5% 하락 시 알림","📈 수익률 +10%\n수익률이 +10% 도달 시 알림","⏱ 30분 동안 매매하지 않기\n지정한 시간 동안 매매를 쉬도록 알림","🔔 전일 고점 돌파 시\n전일 최고가 돌파 시 알림","🛑 손절 라인\n-3% / -5% 등 직접 설정"}; for(String s:a){ LinearLayout r=row(); TextView t=cardText(s,14,white); r.addView(t,new LinearLayout.LayoutParams(0,dp(76),1)); Button set=btn("설정",Color.rgb(34,40,51)); r.addView(set,new LinearLayout.LayoutParams(dp(76),dp(76))); content.addView(r); set.setOnClickListener(v->Toast.makeText(this,"알림 프리셋을 설정했어요.",Toast.LENGTH_SHORT).show()); } section("안내"); content.addView(cardText("실시간 가격 데이터와 증권사 계좌를 직접 연결하지 않는 로컬 알림 설계입니다.",13,muted)); }
    void showRewards(){ base(); header("참는 행동을 기록하고 성장하세요"); section("현재 보상"); content.addView(cardText("🐜  초보 투자자  Lv.3\n\nPOINT  " + points + "P\n\n다음 레벨까지 250P\n██████████████░░░░",16,white)); section("오늘의 보상"); content.addView(cardText("✓ 30초 타이머 완료        +50P\n✓ 매매 쉬기 성공           +100P\n✓ 연속 3일 충동매매 방지    +300P",14,white)); section("연속 기록"); content.addView(cardText("🔥  연속 5일\n\n차분하게 기록하고 기다린 날이 5일째예요.",15,white)); }
    void showMore(){ base(); header("ANTVANCE 설정"); section("화면 제어"); Button ov=btn("화면 오버레이 권한 설정",red); content.addView(ov,new LinearLayout.LayoutParams(-1,dp(52))); ov.setOnClickListener(v->{ try{startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:"+getPackageName())));}catch(Exception e){} }); section("매매 원칙"); content.addView(cardText("1. 계획 없는 매매는 하지 않는다.\n2. 감정이 올라오면 30초 기다린다.\n3. 손실을 만회하려고 즉시 재진입하지 않는다.",14,white)); section("앱 정보"); content.addView(cardText("ANTVANCE FINANCE  ·  v1.0\n\n투자 결정을 대신하지 않고 기록과 자기통제를 돕는 도구입니다.",13,muted)); }
    void save(){ prefs.edit().putInt("waits",waits).putInt("points",points).putInt("trades",trades).apply(); }
}
