package com.antvance.finance;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.security.MessageDigest;
import java.security.SecureRandom;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

public class MainActivity extends Activity {
    LinearLayout root, content, setupBody;
    TextView setupProgress, setupTitle;
    android.content.SharedPreferences prefs;
    int red=Color.rgb(255,59,69), green=Color.rgb(70,214,155), bg=Color.rgb(5,7,11), panel=Color.rgb(17,21,29), muted=Color.rgb(143,152,168), white=Color.rgb(245,247,250);
    int waits, points, trades, cooldownSeconds=30, dailyLimit=5, disciplineLevel=2, emotionRisk=0;
    boolean requireUnlock=false;
    String preferredMessage="충동은 멈추고, 실력은 쌓는다.";
    int setupStep=0, planning=-1;
    EditText passwordInput, passwordConfirm;

    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(2),dp(2),dp(2),dp(2));return t;}
    GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
    Button btn(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(white);b.setTextSize(14);b.setAllCaps(false);b.setBackground(shape(color,18));b.setPadding(dp(12),0,dp(12),0);return b;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    TextView small(String s){return tv(s,12,muted);}
    TextView card(String s,float size){TextView t=tv(s,size,white);t.setPadding(dp(14),dp(12),dp(14),dp(12));t.setBackground(shape(panel,16));return t;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);prefs=getSharedPreferences("data",0);load();if(!prefs.getBoolean("setup_complete",false))showSetup();else showHome();}
    void load(){waits=prefs.getInt("waits",0);points=prefs.getInt("points",0);trades=prefs.getInt("trades",0);cooldownSeconds=prefs.getInt("cooldown",30);dailyLimit=prefs.getInt("daily_limit",5);disciplineLevel=prefs.getInt("discipline",prefs.getInt("protection",2));emotionRisk=prefs.getInt("emotion_risk",0);preferredMessage=prefs.getString("message",preferredMessage);}
    void save(){prefs.edit().putInt("waits",waits).putInt("points",points).putInt("trades",trades).putInt("cooldown",cooldownSeconds).putInt("daily_limit",dailyLimit).putInt("discipline",disciplineLevel).remove("protection").putInt("emotion_risk",emotionRisk).putString("message",preferredMessage).apply();}

    void showSetup(){
        root=col();root.setBackgroundColor(bg);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout outer=col();outer.setPadding(dp(22),dp(28),dp(22),dp(24));sc.addView(outer);
        TextView logo=tv("ANTVANCE\nFINANCE",25,white);logo.setTypeface(null,1);outer.addView(logo);setupProgress=small("초기 설정 1 / 6");setupProgress.setPadding(0,dp(10),0,dp(18));outer.addView(setupProgress);setupTitle=tv("나만의 절제 설정을\n만들어볼게요",27,white);setupTitle.setTypeface(null,1);outer.addView(setupTitle);
        TextView intro=small("처음 한 번만 설정하면 됩니다. 답변을 바탕으로 앱의 절제 강도와 기본값을 맞춥니다.");intro.setPadding(0,dp(10),0,dp(18));outer.addView(intro);setupBody=col();outer.addView(setupBody);
        LinearLayout buttons=row();Button back=btn("이전",Color.rgb(34,40,51)),next=btn("다음",red);buttons.addView(back,new LinearLayout.LayoutParams(0,dp(54),1));buttons.addView(next,new LinearLayout.LayoutParams(0,dp(54),1));outer.addView(buttons);back.setOnClickListener(v->{if(setupStep>0){setupStep--;renderSetup();}});next.setOnClickListener(v->{if(validateSetup()){if(setupStep<5){setupStep++;renderSetup();}else finishSetup();}});root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);renderSetup();
    }
    TextView q(String s){TextView t=tv(s,16,white);t.setTypeface(null,1);t.setPadding(0,dp(10),0,dp(10));setupBody.addView(t);return t;}
    EditText input(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(white);e.setTextSize(16);e.setSingleLine(true);e.setInputType(type);e.setPadding(dp(14),0,dp(14),0);e.setBackground(shape(panel,14));setupBody.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));return e;}
    RadioGroup choices(String... values){RadioGroup g=new RadioGroup(this);g.setOrientation(RadioGroup.VERTICAL);for(String v:values){RadioButton r=new RadioButton(this);r.setId(View.generateViewId());r.setText(v);r.setTextColor(white);r.setTextSize(15);r.setButtonTintList(new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{red,muted}));r.setPadding(dp(8),dp(4),dp(8),dp(4));g.addView(r,new RadioGroup.LayoutParams(-1,dp(52)));}setupBody.addView(g);return g;}
    int index(RadioGroup g,int id){View v=g.findViewById(id);return v==null?-1:g.indexOfChild(v);}
    void renderSetup(){setupBody.removeAllViews();setupProgress.setText("초기 설정 "+(setupStep+1)+" / 6");switch(setupStep){case 0:security();break;case 1:emotionStep();break;case 2:planningStep();break;case 3:controlStep();break;case 4:limitsStep();break;default:messageStep();}}
    void security(){q("앱 잠금 비밀번호");passwordInput=input("4자리 이상 비밀번호",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);q("비밀번호 확인");passwordConfirm=input("같은 비밀번호를 다시 입력",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);setupBody.addView(card("앱 잠금은 비밀번호로만 해제합니다. 생체인식은 사용하지 않습니다.",13));}
    void emotionStep(){q("손실이 생겼을 때 나에게 가장 가까운 모습은?");RadioGroup g=choices("별로 신경 쓰지 않음","조금 신경 쓰임","만회하고 싶은 마음이 생김","바로 다시 매매하고 싶어짐");g.setOnCheckedChangeListener((a,id)->emotionRisk=index(g,id));q("수익이 생겼을 때 나에게 가장 가까운 모습은?");choices("계획대로 멈춤","조금 더 지켜봄","욕심이 생김","계속 매매하고 싶어짐");}
    void planningStep(){q("매매 전에 계획을 세우는 편인가요?");RadioGroup g=choices("항상 세움","대부분 세움","가끔 세움","거의 세우지 않음");g.setOnCheckedChangeListener((a,id)->planning=index(g,id));q("절제에 도움이 될 것 같은 방식은?");choices("짧은 알림","잠깐 기다리기","강한 화면 경고","기록을 먼저 작성하기");}
    void calculateRecommended(){int e=Math.max(0,emotionRisk),p=Math.max(0,planning);disciplineLevel=Math.max(1,Math.min(4,2+(e>=2?1:0)+(p>=2?1:0)));cooldownSeconds=new int[]{10,20,30,60}[disciplineLevel-1];}
    void controlStep(){calculateRecommended();q("답변을 바탕으로 계산된 권장 절제 수준");setupBody.addView(card("절제 수준  "+disciplineLevel+" / 4\n기본 대기시간  "+cooldownSeconds+"초\n\n이 값은 시장을 판단하는 값이 아니라, 사용자가 정한 자기통제 강도를 위한 값입니다.",14));q("원하는 절제 강도를 직접 선택할 수도 있어요.");RadioGroup g=choices("1  부드러움 — 알림 중심","2  보통 — 대기 + 알림","3  강함 — 대기 + 반복 경고","4  매우 강함 — 긴 대기 + 강한 경고");g.check(g.getChildAt(disciplineLevel-1).getId());g.setOnCheckedChangeListener((a,id)->{int i=index(g,id);if(i>=0){disciplineLevel=i+1;cooldownSeconds=new int[]{10,20,30,60}[i];}});}
    void limitsStep(){q("하루에 앱에서 관리하고 싶은 최대 매매 횟수");EditText e=input("예: 5",InputType.TYPE_CLASS_NUMBER);e.setText(""+dailyLimit);e.setTag("limit");q("매매 전에 기다리고 싶은 시간");RadioGroup g=choices("10초","20초","30초","60초","120초");int i=cooldownSeconds==10?0:cooldownSeconds==20?1:cooldownSeconds==30?2:cooldownSeconds==60?3:4;g.check(g.getChildAt(i).getId());g.setOnCheckedChangeListener((a,id)->{int n=index(g,id);if(n>=0)cooldownSeconds=new int[]{10,20,30,60,120}[n];});}
    void messageStep(){q("경고가 뜰 때 어떤 문구가 가장 도움이 되나요?");RadioGroup g=choices("잠깐 멈추고 다시 생각하기","내가 세운 계획을 확인하기","지금 꼭 필요한 행동인지 확인하기","차분하게 기록하고 기다리기");g.setOnCheckedChangeListener((a,id)->{String[] m={"잠깐 멈추고 다시 생각하기","내가 세운 계획을 확인하기","지금 꼭 필요한 행동인지 확인하기","차분하게 기록하고 기다리기"};int i=index(g,id);if(i>=0)preferredMessage=m[i];});q("최종 설정 확인");setupBody.addView(card("절제 수준  "+disciplineLevel+" / 4\n대기시간  "+cooldownSeconds+"초\n하루 관리 횟수  "+dailyLimit+"회\n\n완료를 누르면 이 설정으로 앱이 시작됩니다.",14));}
    boolean validateSetup(){if(setupStep==0){String a=passwordInput.getText().toString(),b=passwordConfirm.getText().toString();if(a.length()<4){toast("비밀번호는 4자리 이상으로 설정해주세요.");return false;}if(!a.equals(b)){toast("비밀번호가 서로 다릅니다.");return false;}savePassword(a);}if(setupStep==4){View v=setupBody.findViewWithTag("limit");try{dailyLimit=Math.max(1,Math.min(100,Integer.parseInt(((EditText)v).getText().toString())));}catch(Exception e){toast("하루 관리 횟수를 숫자로 입력해주세요.");return false;}}return true;}
    void savePassword(String p){try{byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);byte[] hash=derive(p.toCharArray(),salt);prefs.edit().putString("pw_salt",hex(salt)).putString("pw_hash",hex(hash)).apply();}catch(Exception e){toast("비밀번호 저장에 실패했습니다.");}}
    byte[] derive(char[] p,byte[] salt)throws Exception{PBEKeySpec s=new PBEKeySpec(p,salt,120000,256);byte[] h=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(s).getEncoded();s.clearPassword();return h;}
    String hex(byte[] a){StringBuilder s=new StringBuilder();for(byte b:a)s.append(String.format("%02x",b));return s.toString();}
    byte[] unhex(String s){byte[] a=new byte[s.length()/2];for(int i=0;i<a.length;i++)a[i]=(byte)Integer.parseInt(s.substring(i*2,i*2+2),16);return a;}
    void finishSetup(){prefs.edit().putBoolean("setup_complete",true).apply();waits=0;points=0;trades=0;save();showHome();}

    void base(){root=col();root.setBackgroundColor(bg);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=col();content.setPadding(dp(18),dp(18),dp(18),dp(18));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=row();nav.setPadding(dp(6),dp(8),dp(6),dp(8));nav.setBackgroundColor(Color.rgb(9,12,17));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);addNav(nav,"⌂\n홈",()->showHome());addNav(nav,"▣\n종목",()->showStocks());addNav(nav,"↕\n모의거래",()->showTrade());addNav(nav,"▤\n일지",()->showJournal());addNav(nav,"◈\n분석",()->showAnalysis());addNav(nav,"⋯\n더보기",()->showMore());}
    void addNav(LinearLayout n,String s,Runnable r){TextView t=tv(s,10,muted);t.setGravity(Gravity.CENTER);n.addView(t,new LinearLayout.LayoutParams(0,-1,1));t.setOnClickListener(v->r.run());}
    void header(String sub){LinearLayout h=row();TextView logo=tv("ANTVANCE\nFINANCE",16,white);logo.setTypeface(null,1);h.addView(logo,new LinearLayout.LayoutParams(0,dp(52),1));TextView gear=tv("⚙",23,white);gear.setGravity(Gravity.CENTER);h.addView(gear,new LinearLayout.LayoutParams(dp(45),dp(52)));gear.setOnClickListener(v->showMore());content.addView(h);content.addView(small(sub));}
    void section(String s){TextView t=tv(s,15,white);t.setTypeface(null,1);t.setPadding(0,dp(18),0,dp(10));content.addView(t);}
    void showHome(){base();header("실제 시장을 바탕으로 연습하는 모의주식");LinearLayout st=row();st.addView(stat("가상자산","₩10,000,000","모의투자"),new LinearLayout.LayoutParams(0,dp(92),1));st.addView(stat("오늘 매매",""+trades+"회","설정 "+dailyLimit+"회 이하"),new LinearLayout.LayoutParams(0,dp(92),1));st.addView(stat("절제 수준",""+disciplineLevel+"/4","사용자 설정"),new LinearLayout.LayoutParams(0,dp(92),1));content.addView(st);section("시장 요약");content.addView(card("삼성전자   88,500원   +1.14%\nSK하이닉스   326,500원   -0.76%\n현대차   468,000원   +0.43%\n\n※ 현재 표시되는 종목 정보는 앱의 모의 데이터입니다. 실제 시세 API 연동 시 이 영역을 실제 시장 데이터로 교체합니다.",14));section("멘탈 온도계");int mental=Math.max(0,Math.min(100,75-emotionRisk*12));content.addView(card("현재 상태  "+mental+"%\n\n"+bar(mental)+"\n\n최근 입력한 감정 기록을 바탕으로 표시하는 참고 지표입니다.",14));LinearLayout a=row();Button w=btn(cooldownSeconds+"초 기다리기",red),j=btn("매매일지 기록",Color.rgb(34,40,51));a.addView(w,new LinearLayout.LayoutParams(0,dp(52),1));a.addView(j,new LinearLayout.LayoutParams(0,dp(52),1));content.addView(a);w.setOnClickListener(v->cooldown());j.setOnClickListener(v->showJournal());}
    LinearLayout stat(String a,String b,String c){LinearLayout l=col();l.setPadding(dp(10),dp(10),dp(10),dp(10));l.setBackground(shape(panel,14));l.addView(small(a));TextView y=tv(b,17,white);y.setTypeface(null,1);l.addView(y);l.addView(small(c));return l;}
    String bar(int n){StringBuilder s=new StringBuilder();int on=n/5;for(int i=0;i<20;i++)s.append(i<on?"█":"░");return s.toString();}
    void cooldown(){final Dialog d=new Dialog(this);LinearLayout l=col();l.setPadding(dp(24),dp(24),dp(24),dp(20));l.setBackground(shape(Color.rgb(10,13,19),26));TextView x=tv("잠깐!\n다시 한 번 생각해보세요.",20,white);x.setTypeface(null,1);l.addView(x);TextView timer=tv(""+cooldownSeconds,54,red);timer.setGravity(Gravity.CENTER);l.addView(timer,new LinearLayout.LayoutParams(-1,dp(110)));l.addView(card("“"+preferredMessage+"”\n\n지금 행동이 내가 정한 계획에 포함되어 있나요?",14));Button wait=btn("기다릴게요  (+100P)",red);l.addView(wait,new LinearLayout.LayoutParams(-1,dp(52)));Button close=btn("닫기",Color.TRANSPARENT);l.addView(close,new LinearLayout.LayoutParams(-1,dp(48)));d.setContentView(l);d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(dp(340),-2);}});final int[] sec={cooldownSeconds};Handler h=new Handler();Runnable rr=new Runnable(){public void run(){if(sec[0]>0){timer.setText(""+sec[0]);sec[0]--;h.postDelayed(this,1000);}else{timer.setText("✓");timer.setTextColor(green);wait.setText("기다리기 성공  +100P");}}};wait.setOnClickListener(v->{if(sec[0]<=0){waits++;points+=100;save();d.dismiss();showHome();}else toast("타이머가 끝날 때까지 기다려주세요.");});close.setOnClickListener(v->d.dismiss());d.show();h.post(rr);}
    void showStocks(){base();header("실제 종목을 바탕으로 보는 연습용 시장");section("관심 종목");for(String s:new String[]{"삼성전자   88,500원  +1.14%","SK하이닉스   326,500원  -0.76%","현대차   468,000원  +0.43%","애플   $246.70  +0.31%"}){Button b=btn(s,Color.rgb(24,29,39));content.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->showStockDetail(s));}section("안내");content.addView(card("실제 주문 없이 가상자금으로 연습합니다. 시세 데이터는 API 연결 전까지 모의 데이터로 표시됩니다.",13));}
    void showStockDetail(String s){base();header("종목 상세");content.addView(card(s+"\n\n가격 차트\n\n▁▂▃▂▄▅▆▅▇█▆▇▇█\n\n1일   1주   1개월   1년\n\n거래량  12.4M\n고가  90,200원   저가  87,100원",15));Button b=btn("모의거래 화면으로",red);content.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->showTrade());}
    void showTrade(){base();header("실제 주가 기반 모의거래");content.addView(card("가상 잔고\n₩10,000,000\n\n실제 돈이 아닌 모의자금입니다.",16));section("주문");EditText stock=inputTrade("종목명 또는 종목코드");EditText qty=inputTrade("수량",true);LinearLayout r=row();Button buy=btn("가상 매수",red),sell=btn("가상 매도",Color.rgb(34,40,51));r.addView(buy,new LinearLayout.LayoutParams(0,dp(52),1));r.addView(sell,new LinearLayout.LayoutParams(0,dp(52),1));content.addView(r);View.OnClickListener o=v->{trades++;save();toast("모의거래가 기록되었습니다. 실제 주문은 실행되지 않습니다.");};buy.setOnClickListener(o);sell.setOnClickListener(o);section("최근 거래");content.addView(card("거래내역이 여기에 표시됩니다.\n\n※ 실제 주문/결제 기능은 포함하지 않습니다.",14));}
    EditText inputTrade(String h){return inputTrade(h,false);} EditText inputTrade(String h,boolean num){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(muted);e.setTextColor(white);e.setInputType(num?InputType.TYPE_CLASS_NUMBER:InputType.TYPE_CLASS_TEXT);e.setSingleLine(true);e.setBackground(shape(panel,14));e.setPadding(dp(14),0,dp(14),0);content.addView(e,new LinearLayout.LayoutParams(-1,dp(52)));return e;}
    void showJournal(){base();header("캡처와 감정으로 매매일지를 기록");section("체결 화면 캡처");content.addView(card("📷 체결 화면 이미지를 선택하면 기록 흐름을 이어갈 수 있습니다.",14));Button p=btn("캡처 이미지 선택",red);content.addView(p,new LinearLayout.LayoutParams(-1,dp(52)));p.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);});section("감정 태그");content.addView(card("🙂 차분함     😟 불안     😡 욕심     😔 후회",14));Button saveb=btn("일지 저장하기",red);content.addView(saveb,new LinearLayout.LayoutParams(-1,dp(52)));saveb.setOnClickListener(v->toast("매매일지가 저장됐어요."));}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==101&&c==RESULT_OK&&d!=null)toast("캡처를 불러왔어요.");}
    void showAnalysis(){base();header("나의 모의거래 분석");content.addView(card("총 거래 횟수  "+trades+"회\n참은 횟수  "+waits+"회\n절제 수준  "+disciplineLevel+"/4\n\n※ 수익 예측이나 매수·매도 추천을 하지 않습니다.",15));section("절제 기록");content.addView(card("기다리기 성공 +100P\n충동매매를 줄이기 위한 행동 기록을 확인하세요.",14));}
    void showMore(){base();header("ANTVANCE 설정");section("보안");Button lock=btn("앱 잠금 테스트",red);content.addView(lock,new LinearLayout.LayoutParams(-1,dp(52)));lock.setOnClickListener(v->showLock());Button reset=btn("초기 설정 다시 하기",Color.rgb(34,40,51));content.addView(reset,new LinearLayout.LayoutParams(-1,dp(52)));reset.setOnClickListener(v->{prefs.edit().putBoolean("setup_complete",false).apply();setupStep=0;showSetup();});section("화면 제어");Button ov=btn("화면 오버레이 권한 설정",red);content.addView(ov,new LinearLayout.LayoutParams(-1,dp(52)));ov.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,android.net.Uri.parse("package:"+getPackageName())));}catch(Exception e){}});section("내 설정");content.addView(card("대기시간  "+cooldownSeconds+"초\n하루 관리 횟수  "+dailyLimit+"회\n절제 수준  "+disciplineLevel+"/4\n생체인식  미사용\n\n경고 문구\n“"+preferredMessage+"”",14));}
    void showLock(){final Dialog d=new Dialog(this);LinearLayout l=col();l.setPadding(dp(24),dp(24),dp(24),dp(20));l.setBackground(shape(Color.rgb(10,13,19),26));TextView t=tv("ANTVANCE FINANCE\n잠금 해제",21,white);t.setTypeface(null,1);l.addView(t);EditText p=new EditText(this);p.setHint("비밀번호");p.setHintTextColor(muted);p.setTextColor(white);p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);p.setSingleLine(true);p.setBackground(shape(panel,14));l.addView(p,new LinearLayout.LayoutParams(-1,dp(54)));Button u=btn("잠금 해제",red);l.addView(u,new LinearLayout.LayoutParams(-1,dp(52)));d.setContentView(l);d.setOnShowListener(v->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(dp(340),-2);}});d.setCancelable(false);u.setOnClickListener(v->{if(checkPassword(p.getText().toString()))d.dismiss();else toast("비밀번호가 맞지 않습니다.");});d.show();}
    boolean checkPassword(String p){try{byte[] salt=unhex(prefs.getString("pw_salt",""));byte[] expected=unhex(prefs.getString("pw_hash",""));return MessageDigest.isEqual(expected,derive(p.toCharArray(),salt));}catch(Exception e){return false;}}
    @Override protected void onPause(){super.onPause();if(prefs!=null&&prefs.getBoolean("setup_complete",false)&&!isChangingConfigurations())requireUnlock=true;}
    @Override protected void onResume(){super.onResume();if(requireUnlock&&prefs!=null&&prefs.getBoolean("setup_complete",false)){requireUnlock=false;showLock();}}
}