package com.antvance.finance;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import androidx.biometric.BiometricManager;
import androidx.biometric.BiometricPrompt;
import androidx.core.content.ContextCompat;
import androidx.fragment.app.FragmentActivity;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.security.SecureRandom;
import java.util.*;
import java.util.concurrent.*;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

public class MainActivity extends FragmentActivity {
    LinearLayout root, content, setupBody;
    SharedPreferences prefs;
    final int BG=Color.rgb(5,8,13), CARD=Color.rgb(15,21,30), CARD2=Color.rgb(20,28,39), WHITE=Color.rgb(244,247,251), MUTED=Color.rgb(137,151,168), RED=Color.rgb(255,57,70), GREEN=Color.rgb(49,211,127), BLUE=Color.rgb(80,150,255), DIV=Color.rgb(38,48,62);
    ExecutorService api=Executors.newFixedThreadPool(3);
    String apiKey="";
    int marketTab=0;
    final ArrayList<Stock> stocks=new ArrayList<>();
    final String[] tabNames={"전체","KOSPI","KOSDAQ"};
    final String[][] seed={{"005930","삼성전자","KOSPI"},{"000660","SK하이닉스","KOSPI"},{"373220","LG에너지솔루션","KOSPI"},{"005380","현대차","KOSPI"},{"035420","NAVER","KOSPI"},{"035720","카카오","KOSPI"},{"068270","셀트리온","KOSPI"},{"012330","현대모비스","KOSPI"},{"247540","에코프로비엠","KOSDAQ"},{"086520","에코프로","KOSDAQ"},{"263750","펄어비스","KOSDAQ"},{"035900","JYP Ent.","KOSDAQ"}};

    static class Stock { String symbol,name,market; double price,change,open,high,low,prev,volume; boolean loaded; Stock(String s,String n,String m){symbol=s;name=n;market=m;} }

    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    TextView bold(String s,float size){TextView t=text(s,size,WHITE);t.setTypeface(null,1);return t;}
    TextView small(String s){return text(s,11,MUTED);}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackground(bg(c,14));b.setPadding(dp(10),0,dp(10),0);return b;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);prefs=getSharedPreferences("data",0);apiKey=prefs.getString("td_api_key","");seedStocks();if(!prefs.getBoolean("setup_complete",false))showSetup();else showHome();}
    void seedStocks(){stocks.clear();for(String[] s:seed)stocks.add(new Stock(s[0],s[1],s[2]));}

    void base(){root=col();root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=col();content.setPadding(dp(18),dp(12),dp(18),dp(18));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=row();nav.setPadding(dp(5),dp(4),dp(5),dp(6));nav.setBackgroundColor(Color.rgb(9,13,19));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(76)));navItem(nav,"⌂","홈",()->showHome());navItem(nav,"▥","시장",()->showMarket());navItem(nav,"▣","포트폴리오",()->showPortfolio());navItem(nav,"◈","분석",()->showAnalysis());navItem(nav,"☰","더보기",()->showMore());setContentView(root);}
    void navItem(LinearLayout n,String icon,String label,Runnable r){LinearLayout x=col();x.setGravity(Gravity.CENTER);TextView i=text(icon,23,WHITE);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(-1,dp(34)));TextView l=text(label,10,MUTED);l.setGravity(Gravity.CENTER);x.addView(l,new LinearLayout.LayoutParams(-1,dp(22)));n.addView(x,new LinearLayout.LayoutParams(0,-1,1));x.setOnClickListener(v->r.run());}
    void header(String title,String subtitle){LinearLayout h=row();TextView logo=bold("ANTVANCE\nFINANCE",15);h.addView(logo,new LinearLayout.LayoutParams(0,dp(52),1));TextView s=text("⌕",28,WHITE);s.setGravity(Gravity.CENTER);h.addView(s,new LinearLayout.LayoutParams(dp(42),dp(52)));TextView n=text("●",15,RED);n.setGravity(Gravity.CENTER);h.addView(n,new LinearLayout.LayoutParams(dp(34),dp(52)));content.addView(h);TextView t=bold(title,26);t.setPadding(0,dp(7),0,0);content.addView(t);content.addView(small(subtitle));}
    void section(String s){TextView t=bold(s,15);t.setPadding(0,dp(20),0,dp(9));content.addView(t);}
    TextView card(String s,float size){TextView t=text(s,size,WHITE);t.setPadding(dp(14),dp(13),dp(14),dp(13));t.setBackground(bg(CARD,16));return t;}
    TextView chip(String s,boolean selected){TextView t=text(s,12,selected?WHITE:MUTED);t.setGravity(Gravity.CENTER);t.setPadding(dp(14),0,dp(14),0);t.setBackground(bg(selected?RED:CARD2,18));return t;}

    void showHome(){base();header("홈","시장 데이터를 한눈에 확인하고 모의투자를 기록하세요.");section("시장 요약");LinearLayout hero=col();hero.setPadding(dp(16),dp(15),dp(16),dp(15));hero.setBackground(bg(CARD2,18));hero.addView(small("MARKET DATA"));TextView h=bold("주요 종목 시세",19);h.setPadding(0,dp(5),0,dp(5));hero.addView(h);hero.addView(small("실제 API 데이터 · 주문은 지원하지 않음"));content.addView(hero);section("관심 종목");for(int i=0;i<3;i++)addStockRow(stocks.get(i),false);section("모의투자");LinearLayout p=row();p.setPadding(dp(14),dp(14),dp(14),dp(14));p.setBackground(bg(CARD,16));LinearLayout a=col();a.addView(small("가상자산"));a.addView(bold("₩10,000,000",20));a.addView(small("모의계좌 · 실제 자금 없음"));p.addView(a,new LinearLayout.LayoutParams(0,dp(76),1));TextView q=bold("→",24);p.addView(q,new LinearLayout.LayoutParams(dp(45),dp(76)));content.addView(p);for(int i=0;i<3;i++)loadQuote(stocks.get(i),null);}

    void showMarket(){base();header("시장","전체 시장과 거래소별 종목을 실제 데이터로 확인합니다.");LinearLayout tabs=row();tabs.setPadding(0,dp(13),0,dp(8));for(int i=0;i<3;i++){final int k=i;TextView c=chip(tabNames[i],marketTab==i);tabs.addView(c,new LinearLayout.LayoutParams(0,dp(42),1));c.setOnClickListener(v->{marketTab=k;showMarket();});}content.addView(tabs);LinearLayout tools=row();TextView title=bold(marketTab==0?"전체 종목":marketTab==1?"KOSPI 종목":"KOSDAQ 종목",17);tools.addView(title,new LinearLayout.LayoutParams(0,dp(44),1));TextView refresh=button("↻ 새로고침",CARD2);tools.addView(refresh,new LinearLayout.LayoutParams(dp(108),dp(40)));refresh.setOnClickListener(v->{seedStocks();showMarket();});content.addView(tools);content.addView(small("종목명 / 현재가 / 등락률 / 거래량"));for(Stock s:stocks){if(marketTab==1&&!s.market.equals("KOSPI"))continue;if(marketTab==2&&!s.market.equals("KOSDAQ"))continue;addStockRow(s,true);loadQuote(s,null);}}
    void addStockRow(Stock s,boolean divider){LinearLayout box=col();box.setPadding(dp(4),dp(13),dp(4),dp(13));if(divider)box.setBackground(bg(CARD,14));LinearLayout top=row();LinearLayout name=col();TextView n=bold(s.name,15);name.addView(n);name.addView(small(s.symbol+" · "+s.market));top.addView(name,new LinearLayout.LayoutParams(0,dp(55),1));LinearLayout val=col();val.setGravity(Gravity.RIGHT);TextView price=bold(s.loaded?money(s.price):"—",16);price.setGravity(Gravity.RIGHT);val.addView(price);TextView ch=text(s.loaded?pct(s.change):"API 대기",12,s.loaded?(s.change>=0?RED:BLUE):MUTED);ch.setGravity(Gravity.RIGHT);val.addView(ch);top.addView(val,new LinearLayout.LayoutParams(dp(118),dp(55)));box.addView(top);if(s.loaded){LinearLayout meta=row();meta.addView(small("거래량 "+compact(s.volume)),new LinearLayout.LayoutParams(0,dp(25),1));meta.addView(small("고가 "+money(s.high)+"  저가 "+money(s.low)),new LinearLayout.LayoutParams(-2,dp(25)));box.addView(meta);}content.addView(box);box.setOnClickListener(v->showStockDetail(s));loadQuote(s,price);}

    void showStockDetail(Stock s){base();TextView back=text("‹  시장",14,MUTED);back.setPadding(0,0,0,dp(8));content.addView(back);back.setOnClickListener(v->showMarket());LinearLayout title=row();LinearLayout n=col();n.addView(bold(s.name,24));n.addView(small(s.symbol+" · "+s.market));title.addView(n,new LinearLayout.LayoutParams(0,dp(70),1));TextView star=text("☆",28,WHITE);title.addView(star,new LinearLayout.LayoutParams(dp(45),dp(60)));content.addView(title);TextView price=bold(s.loaded?money(s.price):"데이터 불러오는 중",30);content.addView(price);TextView change=text(s.loaded?pct(s.change):"",14,s.change>=0?RED:BLUE);content.addView(change);section("가격 차트");LineChart chart=new LineChart(this);chart.setBackground(bg(CARD,16));content.addView(chart,new LinearLayout.LayoutParams(-1,dp(230)));section("시세 정보");LinearLayout grid=col();String[][] rows={{"시가",money(s.open),"고가",money(s.high)},{"저가",money(s.low),"전일 종가",money(s.prev)},{"거래량",compact(s.volume),"상태","API 제공값"}};for(String[] r:rows){LinearLayout rr=row();rr.setPadding(dp(12),dp(10),dp(12),dp(10));rr.addView(small(r[0]),new LinearLayout.LayoutParams(0,dp(38),1));rr.addView(bold(r[1],13),new LinearLayout.LayoutParams(0,dp(38),1));rr.addView(small(r[2]),new LinearLayout.LayoutParams(0,dp(38),1));rr.addView(bold(r[3],13),new LinearLayout.LayoutParams(0,dp(38),1));grid.addView(rr);View d=new View(this);d.setBackgroundColor(DIV);grid.addView(d,new LinearLayout.LayoutParams(-1,1));}content.addView(grid);section("기업 정보");TextView info=card("기업 프로필을 불러오는 중...\n업종 · 산업 · 본사 · 기업 설명\n\nAPI에서 제공되는 경우 상세 정보가 표시됩니다.",13);content.addView(info);loadQuoteFull(s,price,change,chart,info);section("모의거래");LinearLayout trade=row();Button buy=button("모의 매수",RED),sell=button("모의 매도",BLUE);trade.addView(buy,new LinearLayout.LayoutParams(0,dp(54),1));trade.addView(sell,new LinearLayout.LayoutParams(0,dp(54),1));content.addView(trade);buy.setOnClickListener(v->toast("모의 매수 기록됨 · 실제 주문은 전송되지 않습니다."));sell.setOnClickListener(v->toast("모의 매도 기록됨 · 실제 주문은 전송되지 않습니다."));}

    void showPortfolio(){base();header("포트폴리오","가상자산과 보유 종목을 관리합니다.");section("모의 계좌");LinearLayout total=col();total.setPadding(dp(16),dp(16),dp(16),dp(16));total.setBackground(bg(CARD2,18));total.addView(small("TOTAL VIRTUAL VALUE"));total.addView(bold("₩10,000,000",28));total.addView(small("실제 돈·실제 계좌와 연결되지 않음"));content.addView(total);section("보유 종목");content.addView(card("아직 모의 보유 종목이 없습니다.\n시장 탭에서 종목을 열고 모의거래를 기록해보세요.",13));section("모의투자 통계");LinearLayout stats=row();stats.addView(stat("총 거래","0","기록"),new LinearLayout.LayoutParams(0,dp(88),1));stats.addView(stat("승률","—","거래 후 계산"),new LinearLayout.LayoutParams(0,dp(88),1));stats.addView(stat("수익률","—","거래 후 계산"),new LinearLayout.LayoutParams(0,dp(88),1));content.addView(stats);}
    LinearLayout stat(String a,String b,String c){LinearLayout l=col();l.setPadding(dp(10),dp(10),dp(10),dp(10));l.setBackground(bg(CARD,14));l.addView(small(a));l.addView(bold(b,17));l.addView(small(c));return l;}

    void showAnalysis(){base();header("분석","시장 데이터를 읽고 학습하기 위한 화면입니다.");section("종목 데이터 분석");content.addView(card("가격·거래량·기술지표를 기반으로 차트를 읽는 연습을 할 수 있습니다.\n\nAI 추천 매수/매도 기능은 넣지 않고, 데이터 설명과 학습 중심으로 구성합니다.",13));section("오늘 확인할 항목");String[] a={"① 현재가와 전일 대비 변화","② 거래량 변화","③ 고가·저가 범위","④ 이동평균·RSI·MACD 등 기술지표(지원 범위 내)","⑤ 기업 기본정보와 재무 데이터(요금제 지원 시)"};for(String x:a)content.addView(card(x,13));}

    void showMore(){base();header("더보기","앱 설정과 시장 데이터 연결");section("시장 데이터 API");EditText key=new EditText(this);key.setHint("Twelve Data API Key");key.setHintTextColor(MUTED);key.setTextColor(WHITE);key.setSingleLine(true);key.setText(apiKey);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setPadding(dp(14),0,dp(14),0);key.setBackground(bg(CARD,14));content.addView(key,new LinearLayout.LayoutParams(-1,dp(54)));Button save=button("API 키 저장 및 연결 테스트",RED);content.addView(save,new LinearLayout.LayoutParams(-1,dp(50)));save.setOnClickListener(v->{apiKey=key.getText().toString().trim();prefs.edit().putString("td_api_key",apiKey).apply();if(apiKey.isEmpty()){toast("API 키를 입력해주세요.");return;}testApi();});content.addView(card("API 사용 방법\n1. Twelve Data에서 개인 API Key를 발급합니다.\n2. 위 칸에 API Key를 붙여넣습니다.\n3. 저장 후 시장 탭에서 종목을 선택합니다.\n4. 시세·OHLC·거래량·차트·기업정보가 지원 범위에 따라 표시됩니다.\n\n주의: API Key를 GitHub 소스코드에 직접 넣지 마세요. 현재 앱은 기기 내부 설정에 저장합니다.",13));section("보안");Button lock=button("생체인식 잠금 테스트",CARD2);content.addView(lock,new LinearLayout.LayoutParams(-1,dp(50)));lock.setOnClickListener(v->authenticate());content.addView(card("이 앱은 공모전용 모의투자 앱입니다. 실제 증권사 주문·계좌 연결은 지원하지 않습니다.",13));}
    void testApi(){api.submit(()->{try{JSONObject j=get("/quote?symbol=005930&exchange=KRX");runOnUiThread(()->toast(j.optString("status","error").equals("ok")?"API 연결 성공":"API 응답 오류: "+j.optString("message","확인 필요")));}catch(Exception e){runOnUiThread(()->toast("API 연결 실패: "+e.getMessage()));}});}

    void loadQuote(Stock s,TextView target){if(apiKey.isEmpty())return;api.submit(()->{try{JSONObject j=get("/quote?symbol="+URLEncoder.encode(s.symbol,"UTF-8")+"&exchange=KRX");applyQuote(s,j);runOnUiThread(()->{if(target!=null)target.setText(money(s.price));});}catch(Exception ignored){}});}
    void loadQuoteFull(Stock s,TextView price,TextView change,LineChart chart,TextView info){if(apiKey.isEmpty()){price.setText("API 키 필요");return;}api.submit(()->{try{JSONObject q=get("/quote?symbol="+URLEncoder.encode(s.symbol,"UTF-8")+"&exchange=KRX");applyQuote(s,q);JSONObject ts=get("/time_series?symbol="+URLEncoder.encode(s.symbol,"UTF-8")+"&exchange=KRX&interval=1day&outputsize=30");ArrayList<Float> vals=new ArrayList<>();JSONArray a=ts.optJSONArray("values");if(a!=null)for(int i=a.length()-1;i>=0;i--)vals.add((float)a.getJSONObject(i).optDouble("close",0));String inf="기업 기본정보\n"+q.optString("name",s.name)+"\n거래소: "+q.optString("exchange","KRX")+"\n통화: "+q.optString("currency","KRW")+"\n시장 상태: "+(q.optBoolean("is_market_open",false)?"개장":"폐장");runOnUiThread(()->{price.setText(money(s.price));change.setText(pct(s.change));change.setTextColor(s.change>=0?RED:BLUE);chart.setValues(vals);info.setText(inf);});}catch(Exception e){runOnUiThread(()->info.setText("API 데이터를 불러오지 못했습니다.\n"+e.getMessage()));}});}
    void applyQuote(Stock s,JSONObject j){if(!"ok".equals(j.optString("status")))return;s.loaded=true;s.price=j.optDouble("close",j.optDouble("price",0));s.change=j.optDouble("percent_change",0);s.open=j.optDouble("open",0);s.high=j.optDouble("high",0);s.low=j.optDouble("low",0);s.prev=j.optDouble("previous_close",0);s.volume=j.optDouble("volume",0);}
    JSONObject get(String path)throws Exception{URL u=new URL("https://api.twelvedata.com"+path+"&apikey="+URLEncoder.encode(apiKey,"UTF-8"));HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestProperty("Authorization","apikey "+apiKey);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);r.close();return new JSONObject(b.toString());}

    String money(double x){if(x<=0)return "—";return String.format(Locale.KOREA,"₩%,.0f",x);}
    String pct(double x){return String.format(Locale.KOREA,"%+.2f%%",x);}
    String compact(double x){if(x>=100000000)return String.format(Locale.KOREA,"%.1f억",x/100000000);if(x>=10000)return String.format(Locale.KOREA,"%.1f만",x/10000);return String.format(Locale.KOREA,"%,.0f",x);}

    void showSetup(){root=col();root.setBackgroundColor(BG);ScrollView s=new ScrollView(this);LinearLayout body=col();body.setPadding(dp(22),dp(35),dp(22),dp(25));s.addView(body);body.addView(bold("ANTVANCE\nFINANCE",25));body.addView(small("공모전용 금융 데이터·모의투자 앱"));body.addView(bold("기본 설정",26),new LinearLayout.LayoutParams(-1,dp(80)));EditText p=new EditText(this);p.setHint("잠금 비밀번호 4자리 이상");p.setHintTextColor(MUTED);p.setTextColor(WHITE);p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);p.setBackground(bg(CARD,14));p.setPadding(dp(14),0,dp(14),0);body.addView(p,new LinearLayout.LayoutParams(-1,dp(54)));Switch bio=new Switch(this);bio.setText("생체인식 잠금 사용");bio.setTextColor(WHITE);bio.setChecked(true);body.addView(bio);body.addView(card("거래 전 강제 대기시간은 없습니다. 모든 거래 기능은 가상자금 모의거래입니다.",13));Button next=button("시작하기",RED);body.addView(next,new LinearLayout.LayoutParams(-1,dp(56)));next.setOnClickListener(v->{if(p.getText().length()<4){toast("비밀번호를 4자리 이상 입력해주세요.");return;}savePassword(p.getText().toString());prefs.edit().putBoolean("setup_complete",true).putBoolean("biometric",bio.isChecked()).apply();showHome();});root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    void savePassword(String p){try{byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);byte[] h=derive(p.toCharArray(),salt);prefs.edit().putString("pw_salt",hex(salt)).putString("pw_hash",hex(h)).apply();}catch(Exception ignored){}}
    byte[] derive(char[] p,byte[] salt)throws Exception{PBEKeySpec s=new PBEKeySpec(p,salt,120000,256);byte[] h=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(s).getEncoded();s.clearPassword();return h;}
    String hex(byte[] a){StringBuilder b=new StringBuilder();for(byte x:a)b.append(String.format("%02x",x));return b.toString();}

    void authenticate(){if(!prefs.getBoolean("biometric",true)){toast("생체인식이 꺼져 있습니다.");return;}BiometricManager bm=BiometricManager.from(this);int can=bm.canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_STRONG|BiometricManager.Authenticators.BIOMETRIC_WEAK);if(can!=BiometricManager.BIOMETRIC_SUCCESS){toast("사용 가능한 생체인식이 없습니다.");return;}Executor ex=ContextCompat.getMainExecutor(this);BiometricPrompt p=new BiometricPrompt(this,ex,new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){toast("생체인식 인증 성공");}@Override public void onAuthenticationError(int c,CharSequence e){toast("생체인식 인증이 취소되었습니다.");}});BiometricPrompt.PromptInfo i=new BiometricPrompt.PromptInfo.Builder().setTitle("ANTVANCE FINANCE").setSubtitle("생체인식으로 잠금 해제").setNegativeButtonText("취소").build();p.authenticate(i);}

    class LineChart extends View {Paint p=new Paint(3);ArrayList<Float> v=new ArrayList<>();LineChart(Context c){super(c);p.setStrokeWidth(dp(2));}void setValues(ArrayList<Float> a){v=a;invalidate();}protected void onDraw(Canvas c){super.onDraw(c);p.setStyle(Paint.Style.STROKE);p.setColor(DIV);p.setStrokeWidth(1);for(int i=1;i<5;i++)c.drawLine(0,getHeight()*i/5f,getWidth(),getHeight()*i/5f,p);if(v.size()<2)return;float min=Collections.min(v),max=Collections.max(v);if(max==min)max=min+1;p.setColor(v.get(v.size()-1)>=v.get(0)?RED:BLUE);p.setStrokeWidth(dp(3));Path path=new Path();for(int i=0;i<v.size();i++){float x=getWidth()*i/(float)(v.size()-1);float y=getHeight()-((v.get(i)-min)/(max-min))*getHeight()*0.82f-getHeight()*0.08f;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);}}

    @Override protected void onDestroy(){api.shutdownNow();super.onDestroy();}
}
